### ISSUE TITLE
Does it supports kibana 5.1.1 ?

### ISSUE THREAD

**Issue by SuhasUnited90** [JuanCarniglia/area3d_vis#3]

**Comment by JuanCarniglia** [comment]
It should!

**Comment by SuhasUnited90** [comment]
It breaks on kibana 5.1.1 with blank screen with the following error on browser console...
```
commons.bundle.js?v=14566:38 TypeError: Cannot read property 'length' of null
    at Graph3d._getDataPoints (kibana.bundle.js?v=14566:170)
    at Graph3d._readData (kibana.bundle.js?v=14566:170)
    at Graph3d.setData (kibana.bundle.js?v=14566:170)
    at new Graph3d (kibana.bundle.js?v=14566:169)
    at kibana.bundle.js?v=14566:137
    at kibana.bundle.js?v=14566:137
    at Object.fn (commons.bundle.js?v=14566:75)
    at Scope.$digest (commons.bundle.js?v=14566:39)
    at Scope.$apply (commons.bundle.js?v=14566:39)
    at HTMLFormElement.<anonymous> (commons.bundle.js?v=14566:42)
(anonymous) @ commons.bundle.js?v=14566:38
(anonymous) @ commons.bundle.js?v=14566:37
$digest @ commons.bundle.js?v=14566:39
$apply @ commons.bundle.js?v=14566:39
(anonymous) @ commons.bundle.js?v=14566:42
dispatch @ commons.bundle.js?v=14566:28
elemData.handle @ commons.bundle.js?v=14566:28
commons.bundle.js?v=14566:38 Error: Parameter 'start' is not numeric; value: NaN
    at StepNumber.setRange (kibana.bundle.js?v=14566:171)
    at new StepNumber (kibana.bundle.js?v=14566:171)
    at Graph3d._redrawAxis (kibana.bundle.js?v=14566:170)
    at Graph3d.redraw (kibana.bundle.js?v=14566:170)
    at Graph3d.setData (kibana.bundle.js?v=14566:170)
    at new Graph3d (kibana.bundle.js?v=14566:169)
    at kibana.bundle.js?v=14566:137
    at kibana.bundle.js?v=14566:137
    at Object.fn (commons.bundle.js?v=14566:75)
    at Scope.$digest (commons.bundle.js?v=14566:39)
(anonymous) @ commons.bundle.js?v=14566:38
(anonymous) @ commons.bundle.js?v=14566:37
$digest @ commons.bundle.js?v=14566:39
$apply @ commons.bundle.js?v=14566:39
done @ commons.bundle.js?v=14566:37
completeRequest @ commons.bundle.js?v=14566:37
xhr.onload @ commons.bundle.js?v=14566:37
```

**Comment by JuanCarniglia** [comment]
This line should cue us "Error: Parameter 'start' is not numeric; value: NaN" ... The same as issue #5, there seems to be an invalid Data Field being used. Can you paste here the configuration for the view? Thanks.

**Comment by billmetangmo** [comment]
I also had an error when trying to start Kibana 5.1.1 with the plugin : 

{"type":"log","@timestamp":"2017-03-01T12:08:20Z","tags":["fatal"],"pid":20589,"level":"fatal","message":"Unexpected token export","error":{"message":"Unexpected token export","name":"SyntaxError","stack":"/home/cloud-user/kibana-5.1.1-linux-x86_64/src/core_plugins/area3d_vis/index.js:1\n(function (exports, require, module, __filename, __dirname) { export default function (kibana) {\n                                                              ^^^^^^\nSyntaxError: Unexpected token export\n    at Object.exports.runInThisContext (vm.js:76:16)\n    at Module._compile (module.js:542:28)\n    at Module._extensions..js (module.js:579:10)\n    at Object.require.extensions.(anonymous function) [as .js] (/home/cloud-user/kibana-5.1.1-linux-x86_64/node_modules/babel-core/lib/api/register/node.js:214:7)\n    at Module.load (module.js:487:32)\n    at tryModuleLoad (module.js:446:12)\n    at Function.Module._load (module.js:438:3)\n    at Module.require (module.js:497:17)\n    at require (internal/module.js:20:19)\n    at Plugins.<anonymous> (/home/cloud-user/kibana-5.1.1-linux-x86_64/src/server/plugins/plugin_collection.js:66:30)\n    at undefined.next (native)\n    at step (/home/cloud-user/kibana-5.1.1-linux-x86_64/src/server/plugins/plugin_collection.js:22:273)\n    at /home/cloud-user/kibana-5.1.1-linux-x86_64/src/server/plugins/plugin_collection.js:22:443\n    at Plugins.<anonymous> (/home/cloud-user/kibana-5.1.1-linux-x86_64/src/server/plugins/plugin_collection.js:22:99)\n    at KbnServer.<anonymous> (/home/cloud-user/kibana-5.1.1-linux-x86_64/src/server/plugins/scan.js:81:27)\n    at undefined.next (native)"}}
Mar 01 13:08:20 mtb3server-geekshop-environment-compute-kbn-bfa95 kibana[20589]: FATAL /home/cloud-user/kibana-5.1.1-linux-x86_64/src/core_plugins/area3d_vis/index.js:1
Mar 01 13:08:20 mtb3server-geekshop-environment-compute-kbn-bfa95 kibana[20589]: (function (exports, require, module, __filename, __dirname) { export default function (kibana) {
Mar 01 13:08:20 mtb3server-geekshop-environment-compute-kbn-bfa95 kibana[20589]: ^^^^^^
Mar 01 13:08:20 mtb3server-geekshop-environment-compute-kbn-bfa95 kibana[20589]: SyntaxError: Unexpected token export
Mar 01 13:08:20 mtb3server-geekshop-environment-compute-kbn-bfa95 systemd[1]: kibana.service: main process exited, code=exited, status=1/FAILURE
Mar 01 13:08:20 mtb3server-geekshop-environment-compute-kbn-bfa95 systemd[1]: Unit kibana.service entered failed state.
Mar 01 13:08:20 mtb3server-geekshop-environment-compute-kbn-bfa95 systemd[1]: kibana.service failed.

**Comment by JuanCarniglia** [comment]
I added an extra check in the code. Please update and verify if it is now working.

Thanks!

**Comment by jennyHsiao** [comment]
Hi, I'm using kibana 5.2.2 with the plugin. There are error massages:

{"type":"log","@timestamp":"2017-03-16T07:25:02Z","tags":["fatal"],"pid":14637,"level":"fatal","message":"Unexpected token export","error":{"message":"Unexpected token export","name":"SyntaxError","stack":"/home/jenny/kibana-5.2.2-linux-x86_64/src/core_plugins/area3d_vis/index.js:1\n(function (exports, require, module, __filename, __dirname) { export default function (kibana) {\n                                                              ^^^^^^\nSyntaxError: Unexpected token export\n    at Object.exports.runInThisContext (vm.js:76:16)\n    at Module._compile (module.js:542:28)\n    at Module._extensions..js (module.js:579:10)\n    at Object.require.extensions.(anonymous function) [as .js] (/home/jenny/kibana-5.2.2-linux-x86_64/node_modules/babel-core/lib/api/register/node.js:214:7)\n    at Module.load (module.js:487:32)\n    at tryModuleLoad (module.js:446:12)\n    at Function.Module._load (module.js:438:3)\n    at Module.require (module.js:497:17)\n    at require (internal/module.js:20:19)\n    at Plugins.<anonymous> (/home/jenny/kibana-5.2.2-linux-x86_64/src/server/plugins/plugin_collection.js:66:30)\n    at undefined.next (native)\n    at step (/home/jenny/kibana-5.2.2-linux-x86_64/src/server/plugins/plugin_collection.js:22:273)\n    at /home/jenny/kibana-5.2.2-linux-x86_64/src/server/plugins/plugin_collection.js:22:443\n    at Plugins.<anonymous> (/home/jenny/kibana-5.2.2-linux-x86_64/src/server/plugins/plugin_collection.js:22:99)\n    at KbnServer.<anonymous> (/home/jenny/kibana-5.2.2-linux-x86_64/src/server/plugins/scan.js:81:27)\n    at undefined.next (native)"}}
FATAL /home/jenny/kibana-5.2.2-linux-x86_64/src/core_plugins/area3d_vis/index.js:1
(function (exports, require, module, __filename, __dirname) { export default function (kibana) {
                                                              ^^^^^^
SyntaxError: Unexpected token export
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/jenny/kibana-5.2.2-linux-x86_64/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Plugins.<anonymous> (/home/jenny/kibana-5.2.2-linux-x86_64/src/server/plugins/plugin_collection.js:66:30)
    at undefined.next (native)
    at step (/home/jenny/kibana-5.2.2-linux-x86_64/src/server/plugins/plugin_collection.js:22:273)
    at /home/jenny/kibana-5.2.2-linux-x86_64/src/server/plugins/plugin_collection.js:22:443
    at Plugins.<anonymous> (/home/jenny/kibana-5.2.2-linux-x86_64/src/server/plugins/plugin_collection.js:22:99)
    at KbnServer.<anonymous> (/home/jenny/kibana-5.2.2-linux-x86_64/src/server/plugins/scan.js:81:27)
    at undefined.next (native)

Could you help me?

**Comment by bsuvorov** [comment]
Having same error as above ^^^ , please help. your software is in top google search results for 3d kibana visualization. which means => basically your have the most popular 3d visualization tool for kibana out there right now :)

**Comment by JuanCarniglia** [comment]
I just committed a 5.5 compliant version. Please check it.

**Comment by vsnash** [comment]
hey. tried installing it with 5.5 Getting this error.

``` ---> e79c96e3dd47
Removing intermediate container 928beee87cb2
Step 17/21 : RUN cd /usr/share/kibana/plugins/area3d_vis && npm install
 ---> Running in 34a72f7136c5

> dtrace-provider@0.6.0 install /usr/share/kibana/node_modules/dtrace-provider
> node scripts/install.js

kibana@5.5.0 /usr/share/kibana
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN kibana@5.5.0 No license field.
npm ERR! code 1
ERROR: Service 'kibana' failed to build: The command '/bin/sh -c cd /usr/share/kibana/plugins/area3d_vis && npm install' returned a non-zero code: 1```

**Comment by vsnash** [comment]
although when I run ```npm install vis``` it works.

**Comment by JuanCarniglia** [comment]
You probably have no "/usr/share/kibana/plugins/area3d_vis" folder.

I just copy the code over to the src/core_plungins/ folder (on an "area3d_vis" folder) and then run "npm install vis" on that folder, to get Vis.

Then you have to restart Kibana (Probably remove the bundle files beforehand, to get them rebuilt).

Regards
